org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
systemProp.http.proxyHost=10.190.254.20
systemProp.http.proxyPort=80
systemProp.https.proxyHost=10.190.254.20
systemProp.https.proxyPort=80
